import './funcs.js';
import './popap.js';
import './yandexmap.js';
import './megamenu.js';
import './notifier.js';
import './cdek.js';
import './cookie.js';
import './contact-form.js';
import './bitrix24_chat.js';
